CPP=g++
CPPFLAGS=-Wall -std=c++11
MAIN_NAME=main
SOURCE_FILES=single_linked_list.h single_linked_list.cc

main: $(objects)
	$(CPP) $(CPPFLAGS)  $(SOURCE_FILES) -o $(MAIN_NAME)

clean:
	rm -f $(MAIN_NAME)
